GET http://localhost:8082/employee/add?firstName=Ivan&lastName=Ivanov&salary=50000&departmentId=1
####
GET http://localhost:8082/employee/add?firstName=Ivan&lastName=Stepanov&salary=40000&departmentId=2
####
GET http://localhost:8082/employee/add?firstName=Ivan&lastName=Sidorov&salary=30000&departmentId=1
####
GET http://localhost:8082/employee/add?firstName=Ivan&lastName=Egorov&salary=60000&departmentId=2
####
GET http://localhost:8082/departments/all
####
GET http://localhost:8082/departments/all?departmentId=1
####
GET http://localhost:8082/departments/all?departmentId=2